spring.application.name=order-service

server.servlet.context-path=/orders
server.port=9020

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB1
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
